### ISSUE TITLE
Get pushToken is nil

### ISSUE THREAD

**Issue by tema-tian** [klaviyo/klaviyo-swift-sdk#161]
### Description

KlaviyoSwift version 2.2.1 is upgraded to 3.0.3. The pushToken obtained in KlaviyoSDK().pushToken is nil.

     func application(_: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
       KlaviyoSDK().set(pushToken: deviceToken)
       print("PushToken:\(String(describing: KlaviyoSDK().pushToken))")
     }

Print log 

       PushToken:nil

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [discussion](https://github.com/pointfreeco/klaviyo/klaviyo-swift-sdk/discussions).

### Expected behavior

KlaviyoSDK().pushToken has a value, we need to upload it to the server for sending push

### The Klaviyo Swift SDK version information

3.0.3

### Destination operating system

16.7.2

### Xcode version information

15.2

### Swift Compiler version information

```shell
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
```

**Comment by ajaysubra** [comment]
Hey @tema-tian Thanks for reaching out. We don't believe that this is related to migration to `3.0.3` of our SDK. The token is set to the local state after the asynchronous network call and hence there will be a delay for the getter to get the set token. If what you are doing is exclusively for validating that the token is set, you can add a time delay and then call the push token getter. Here's a piece of code you could use for that - 


```swift
    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        print("did register for remote notifications", deviceToken.map { String(format: "%02.2hhx", $0) }.joined())
        KlaviyoSDK().set(pushToken: deviceToken)
        
        // 30s only because our API has a sync interval to avoid consuming too much network bandwidth.
        DispatchQueue.main.asyncAfter(deadline: .now() + 30) {
            print("KlaviyoSDK().pushToken:  ", KlaviyoSDK().pushToken ?? "")
        }
    }
```

We do acknowledge that this may not be an obvious experience and we will look into potentially setting to state before making the async API call for register the push token. 

Please let us know if you have any other questions. Thanks!

**Comment by tema-tian** [comment]
Hey @ajaysubra thanks for your reply. Here I am not verifying whether the token has been set. pushToken is used as the identifier for sending push. After the App is started, the pushToken will be synchronized with the backend server. The delayed return time of 30s is too long. The App may have completed the synchronization of pushToken with the backend server. We need to know exactly when
KlaviyoSDK can return pushToken instead of delaying 30 seconds, or can you provide a callback method so that we can send pushToken to our own service.

**Comment by ajaysubra** [comment]
@tema-tian Thanks for providing context. I do have some follow on questions - can you help me understand what exactly is your use case and why you intent to use the push token from Klaviyo SDK as the source of truth for the APNs push token that is generated by iOS? 

Since you already have the token in app delegate of your application, why not send it to your backend servers from there? 

Again, I want to reiterate that I agree that this is not an ideal experience and understand that the push token getter should be able to return the token after being set. Although, it's a quick change, there are some considerations on our end (with respect to batching requests and the push token workflow) to make which may take some time. In the meantime want to be sure that I understand your use case and make sure you are unblocked.

**Comment by tema-tian** [comment]
Hey @ajaysubra thanks for your reply. Generally, after the third-party push SDK is initialized, the deviceToken will be given to the push SDK, and then the push ID returned by the push SDK will be given to the server for sending push.
If your SDK only performs hex formatting on deviceToken, we can hex format it ourselves and report it to the server. Of course, the premise is that your pushToken generation logic will not change in subsequent updates.
Since the current formatting of deviceToken is only hex formatting, why can’t KlaviyoSDK().pushToken get the value? This seems to be a very simple logic that goes against common sense.

**Comment by ajaysubra** [comment]
@tema-tian In order to make progress on this issue we need to better understand your use case. I would urge you to look at our readme, specifically the [collecting push tokens](https://github.com/klaviyo/klaviyo-swift-sdk?tab=readme-ov-file#collecting-push-tokens) section. Calls to `setToken` containing new tokens will always result in an api request to store it with Klaviyo. Once the token is successfully transmitted it will be reflected in the token state on the sdk. If you are intending to set the push token on your servers independently then you can use the token delivered to your app in the `didRegisterForRemoteNotificationsWithDeviceToken`.

Separately, we will look into making getting a push token more timely.  We will close this issue now but will let you know once we've made the improvements to the push token getter.
